/**
 * PWA identity (SPEC-core "PWA"): one source for the web manifest, the root metadata and the icon
 * generator (`scripts/build-icons.tsx`). Client-safe: plain data only. Colors come from
 * `@/design-system/brand-colors`.
 */
export const APP_NAME = "brahua-os";
export const APP_DESCRIPTION = "Mi segundo cerebro: hábitos, tareas, proyectos y más.";

/** Manifest icons, served from `public/` (generated by `pnpm icons:build`). */
export const MANIFEST_ICONS = [
  { src: "/icons/icon-192.png", size: 192, purpose: "any" },
  { src: "/icons/icon-512.png", size: 512, purpose: "any" },
  { src: "/icons/icon-maskable-512.png", size: 512, purpose: "maskable" },
] as const;
