import {
  Apple,
  AudioWaveform,
  Baby,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Calendar,
  Camera,
  Car,
  Cat,
  Code,
  Coffee,
  Dog,
  Dumbbell,
  Film,
  Flower2,
  Gamepad2,
  Globe,
  GraduationCap,
  Guitar,
  Headphones,
  Heart,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Map as MapIcon,
  Mic,
  Moon,
  Mountain,
  Music,
  Palette,
  PenTool,
  PiggyBank,
  Pill,
  Plane,
  Rocket,
  Shield,
  ShoppingCart,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Target,
  Tent,
  TrendingUp,
  Trophy,
  Users,
  Utensils,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { AreaIconName } from "./areas";

export type { AreaIconName } from "./areas";

/**
 * Curated icon set for life areas. Explicit imports keep the bundle small:
 * the UI can offer these without loading all of Lucide.
 * Keys must match AREA_ICON_NAMES in ./areas (the server-safe list stored in the database).
 */
export const AREA_ICONS = {
  house: House,
  "heart-pulse": HeartPulse,
  wallet: Wallet,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  users: Users,
  plane: Plane,
  "audio-waveform": AudioWaveform,
  apple: Apple,
  baby: Baby,
  bike: Bike,
  "book-open": BookOpen,
  brain: Brain,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  cat: Cat,
  code: Code,
  coffee: Coffee,
  dog: Dog,
  dumbbell: Dumbbell,
  film: Film,
  flower: Flower2,
  gamepad: Gamepad2,
  globe: Globe,
  guitar: Guitar,
  headphones: Headphones,
  heart: Heart,
  landmark: Landmark,
  laptop: Laptop,
  leaf: Leaf,
  lightbulb: Lightbulb,
  map: MapIcon,
  mic: Mic,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  palette: Palette,
  "pen-tool": PenTool,
  "piggy-bank": PiggyBank,
  pill: Pill,
  rocket: Rocket,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  stethoscope: Stethoscope,
  sun: Sun,
  target: Target,
  tent: Tent,
  "trending-up": TrendingUp,
  trophy: Trophy,
  utensils: Utensils,
  wrench: Wrench,
} as const satisfies Record<AreaIconName, LucideIcon>;
