// User-facing copy of the life areas screen (Spanish).
import type { AreaColor, AreaIconName } from "@/design-system/areas";

export const AREAS_COPY = {
  title: "Áreas",
  count: (n: number) => (n === 1 ? "1 área" : `${n} áreas`),
  listLabel: "Tus áreas",
  newArea: "Nueva área",
  editArea: "Editar área",
  editRow: (name: string) => `Editar ${name}`,
  emptyTitle: "Aún no tienes áreas",
  emptyText:
    "Las áreas agrupan tus proyectos, hábitos y gastos por parte de tu vida. Crea la primera con «Nueva área».",
  nameLabel: "Nombre",
  nameHelp: "Hasta 60 caracteres.",
  colorLabel: "Color",
  iconLabel: "Ícono",
  iconHint: "Usa las flechas para moverte por filas y columnas.",
  previewLabel: "Vista previa",
  previewPlaceholder: "Nombre del área",
  previewHint: "Elige un color y un ícono para verla.",
  cancel: "Cancelar",
  create: "Crear área",
  save: "Guardar cambios",
  saving: "Guardando…",
  created: (name: string) => `Área «${name}» creada.`,
  updated: (name: string) => `Cambios guardados en «${name}».`,
  unexpected: "No se pudo guardar. Revisa tu conexión e inténtalo de nuevo.",

  // Order (C6)
  moveUp: (name: string) => `Subir ${name}`,
  moveDown: (name: string) => `Bajar ${name}`,
  drag: (name: string) => `Mover ${name}`,
  dragRole: "elemento ordenable",
  dragInstructions:
    "Para mover un área, pulsa Espacio o Enter, muévela con las flechas arriba y abajo y vuelve a pulsar Espacio o Enter para dejarla. Escape cancela. En pantallas táctiles, mantén presionado y arrastra.",
  position: (index: number, total: number) => `lugar ${index + 1} de ${total}`,
  dragStart: (name: string, place: string) => `Tomaste «${name}», en el ${place}.`,
  dragOver: (name: string, place: string) => `«${name}» está en el ${place}.`,
  dragSame: (name: string, place: string) => `«${name}» quedó en el mismo ${place}.`,
  dragCancel: (name: string, place: string) => `Cancelado. «${name}» volvió al ${place}.`,

  // Archive (C6)
  archive: "Archivar área",
  archiveHelp:
    "Deja de ofrecerse para elementos nuevos; lo que ya la usa la conserva. Puedes desarchivarla cuando quieras.",
  archivedTitle: "Archivadas",
  archivedList: "Áreas archivadas",
  archivedHelp:
    "No se ofrecen para elementos nuevos. Para editar una, desarchívala: vuelve al final de tus áreas.",
  unarchive: "Desarchivar",
  unarchiveRow: (name: string) => `Desarchivar ${name}`,

  // Notices (C6)
  noticesLabel: "Avisos",
  undo: "Deshacer",
  orderTitle: "Orden",
  moved: (name: string, place: string) => `«${name}» pasó al ${place}.`,
  archivedNoticeTitle: "Archivada",
  archivedNotice: (name: string) => `«${name}» se archivó.`,
  restoredTitle: "De vuelta",
  restored: (name: string) => `«${name}» volvió al final de tus áreas.`,
  undoneTitle: "Deshecho",
  orderRestored: "Volvió el orden anterior.",
  backInPlace: (name: string) => `«${name}» volvió a su lugar.`,
  archivedAgain: (name: string) => `«${name}» volvió a Archivadas.`,
  notSavedTitle: "Sin guardar",
  orderFailed: "No se pudo guardar el orden. Inténtalo de nuevo.",
  archiveFailed: (name: string) => `No se pudo archivar «${name}». Inténtalo de nuevo.`,
  unarchiveFailed: (name: string) => `No se pudo desarchivar «${name}». Inténtalo de nuevo.`,
  undoFailed: "No se pudo deshacer. Inténtalo de nuevo.",
} as const;

/** Palette names by color (the palettes are named after the default areas in the code). */
export const AREA_COLOR_LABELS: Record<AreaColor, string> = {
  home: "Ámbar",
  health: "Verde",
  finance: "Turquesa",
  learning: "Índigo",
  work: "Violeta",
  relationships: "Rosa",
  travel: "Celeste",
  hobbies: "Lima",
};

/** Accessible names of the curated icons. */
export const AREA_ICON_LABELS: Record<AreaIconName, string> = {
  house: "Casa",
  "heart-pulse": "Pulso",
  wallet: "Billetera",
  "graduation-cap": "Birrete",
  briefcase: "Maletín",
  users: "Personas",
  plane: "Avión",
  "audio-waveform": "Onda de sonido",
  apple: "Manzana",
  baby: "Bebé",
  bike: "Bicicleta",
  "book-open": "Libro abierto",
  brain: "Cerebro",
  calendar: "Calendario",
  camera: "Cámara",
  car: "Auto",
  cat: "Gato",
  code: "Código",
  coffee: "Café",
  dog: "Perro",
  dumbbell: "Pesa",
  film: "Película",
  flower: "Flor",
  gamepad: "Control de videojuegos",
  globe: "Globo terráqueo",
  guitar: "Guitarra",
  headphones: "Audífonos",
  heart: "Corazón",
  landmark: "Edificio público",
  laptop: "Laptop",
  leaf: "Hoja",
  lightbulb: "Foco",
  map: "Mapa",
  mic: "Micrófono",
  moon: "Luna",
  mountain: "Montaña",
  music: "Música",
  palette: "Paleta de pintor",
  "pen-tool": "Pluma",
  "piggy-bank": "Alcancía",
  pill: "Pastilla",
  rocket: "Cohete",
  shield: "Escudo",
  "shopping-cart": "Carrito de compras",
  sparkles: "Destellos",
  sprout: "Brote",
  star: "Estrella",
  stethoscope: "Estetoscopio",
  sun: "Sol",
  target: "Diana",
  tent: "Carpa",
  "trending-up": "Tendencia al alza",
  trophy: "Trofeo",
  utensils: "Cubiertos",
  wrench: "Llave inglesa",
};
